### PR TITLE
Improve Software.pm

### PR DESCRIPTION
**Pull request by charleneauger**
## Important notes
Please, don't mistake OCSInventory-server with OCSInventory-ocsreports :
* OCSInventory-server : Communication server that manage the inventory
* OCSInventory-ocsreports : Web interface of OCS Inventory

## General informations
Operating system :

## Server informations
Perl version :
Mysql / Mariadb / Percona version :  

## Status
**READY**

## Description

* Remove delete all software function
* Check if software is already in db : 
if true : skip insert and save the id
if false : insert and save the id
* Check if software category is 0
if true : skip
if false : check if software already in this category in db else delete/insert
* Delete all software not in id saved with the hardware_id

### CODE REVIEW

**Comment by jjmg84** [comment]
Hi, i see new errors 
DBD::mysql::st execute failed: Lock wait timeout exceeded; try restarting transaction at /usr/local/share/perl/5.30.0/Apache/Ocsinventory/Server/Inventory/Software.pm line 61.

and in mysql i see too many queryes 

imagen

 This generate too many concurrent connections  (1517) and get mysql server slow.

is it normal?

**Comment by charleneauger** [comment]
Hi @jjmg84 ,

Thanks for your feedback !

* Can you tell me the number of agents you have as well as the average number of simultaneous connections on the /ocsinventory ?
* Can you provide me with the specs of your OCS server and MySQL server (if it's a split infra) ?

Best regards,
Charlene

**Comment by jjmg84** [comment]
Hi, i have +- 17000 computers on OCS, 8 core 64gb ocs server machine, 12core, 16gb mariadb server machine

I think i have troubleshoted the problem, i saw that are many conections that are launching a query to a network table:

SELECT HARDWARE_ID,DESCRIPTION,MACADDR FROM networks WHERE MACADDR=? AND HARDWARE_ID<>?

All of them with a mac of 00:00:00:00:00:00 , i searched and this come from the duplicate.pm, i commented out this:

  # ...and one MAC of this machine
  #for(@{$result->{CONTENT}->{NETWORKS}}){
#    $request = $dbh->prepare('SELECT HARDWARE_ID,DESCRIPTION,MACADDR FROM networks WHERE MACADDR=? AND HARDWARE_ID<>?');
#    $request->execute($_->{MACADDR}, $DeviceID);
#    while($row = $request->fetchrow_hashref()){
#      if(!&_already_in_array($row->{'MACADDR'}, \@bad_mac)){
#        $exist->{$row->{'HARDWARE_ID'}}->{'MACADDRESS'}++;
#      }
#    }
#  }

And now ocs work like a charm, we are observing but now the cpu load on mariadb has lowed and all seems to run fine

**Comment by charleneauger** [comment]
@jjmg84,

I merged the next PR #395 this morning regarding the macaddress :-)

Regards
Charlene

**Pull request merged**
